### ISSUE TITLE
chartCtor is not a function

### ISSUE THREAD

**Issue by hhkaos** [Jimeno0/my-calcite#1]
<img width="1279" alt="screen shot 2016-08-12 at 09 02 24" src="https://cloud.githubusercontent.com/assets/826965/17615056/a0d2caae-606b-11e6-95ca-febc2c27093c.png">

Hi crack, no sé que habrá cambiado pero ya no se muestran las gráficas, a lo mejor conviene que uses una versión de Cedar en local, así no te afectarían las actualizaciones :)

Abrazo!

**Comment by Jimeno0** [comment]
Ostras acabo de verlo

Voy a ver como arreglarlo. Muchas gracias Crack! =)

```
     <https://www.linkedin.com/in/carlos-perez-jimeno-087b3390?trk=nav_responsive_tab_profile_pic>              
```

Carlos Pérez Jimeno  mailto:carlospj@icloud.com• Gis Developer
Technology and Innovation Area • Esri Spain http://www.esri.es/es/
+34.618.623.483 tel:+34-618-623-483
   https://www.linkedin.com/in/carlos-perez-jimeno-087b3390?trk=nav_responsive_tab_profile_pic   https://github.com/Jimeno0   https://twitter.com/jimeno0  http://www.geodevelopers.org/members/200045805
